version: "3.8"

services:
  web:
    build: .
    command: gunicorn rumipress.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    env_file:
      - .env

volumes:
  static_volume:
